package net.ember.embrtrees.datagen;

import net.ember.embrtrees.EmbrTrees;
import net.ember.embrtrees.block.ModBlocks;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.*;
import net.minecraftforge.client.model.generators.BlockStateProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModBlockStateProvider extends BlockStateProvider
{
    public ModBlockStateProvider(PackOutput output, ExistingFileHelper exFileHelper)
    {
        super(output, EmbrTrees.MODID, exFileHelper);
    }

    @Override
    protected void registerStatesAndModels() {
//ASH WOOD
        saplingBlock(ModBlocks.ASH_SAPLING);
        blockWithItem(ModBlocks.ASH_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.ASH_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/ash-log"), new ResourceLocation(EmbrTrees.MODID, "block/ash-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.ASH_WOOD.get(), blockTexture(ModBlocks.ASH_LOG.get()), blockTexture(ModBlocks.ASH_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_ASH_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/ash-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/ash-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_ASH_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/ash-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/ash-stripped-log"));
        blockWithItem(ModBlocks.ASH_PLANKS);
        stairsBlock((StairBlock) ModBlocks.ASH_STAIRS.get(), blockTexture(ModBlocks.ASH_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.ASH_SLAB.get(), blockTexture(ModBlocks.ASH_PLANKS.get()), blockTexture(ModBlocks.ASH_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.ASH_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/ash-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/ash-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.ASH_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/ash-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.ASH_FENCE.get(), blockTexture(ModBlocks.ASH_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.ASH_FENCE_GATE.get(), blockTexture(ModBlocks.ASH_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.ASH_PRESSURE_PLATE.get(), blockTexture(ModBlocks.ASH_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.ASH_BUTTON.get(), models().button("embrtrees:ash-button", blockTexture(ModBlocks.ASH_PLANKS.get())), models().buttonPressed("embrtrees:ash-button-pressed", blockTexture(ModBlocks.ASH_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.ASH_SIGN.get(), (WallSignBlock)ModBlocks.ASH_WALL_SIGN.get(), models().sign("embrtrees:ash-sign", blockTexture(ModBlocks.ASH_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASH_LOG.get(), models().withExistingParent("embrtrees:ash-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.ASH_WOOD.get(), models().withExistingParent("embrtrees:ash-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_ASH_LOG.get(), models().withExistingParent("embrtrees:stripped-ash-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_ASH_WOOD.get(), models().withExistingParent("embrtrees:stripped-ash-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.ASH_STAIRS.get(), models().stairs("embrtrees:ash-stairs", blockTexture(ModBlocks.ASH_PLANKS.get()), blockTexture(ModBlocks.ASH_PLANKS.get()), blockTexture(ModBlocks.ASH_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASH_SLAB.get(), models().slab("embrtrees:ash-slab", blockTexture(ModBlocks.ASH_PLANKS.get()), blockTexture(ModBlocks.ASH_PLANKS.get()), blockTexture(ModBlocks.ASH_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASH_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:ash-trapdoor", blockTexture(ModBlocks.ASH_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.ASH_FENCE.get(), models().fenceInventory("embrtrees:ash-fence", blockTexture(ModBlocks.ASH_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASH_FENCE_GATE.get(), models().fenceGate("embrtrees:ash-fence-gate", blockTexture(ModBlocks.ASH_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASH_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:ash-pressure-plate", blockTexture(ModBlocks.ASH_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASH_BUTTON.get(), models().buttonInventory("embrtrees:ash-button-inventory", blockTexture(ModBlocks.ASH_PLANKS.get())));
//ASTRAL WOOD
        saplingBlock(ModBlocks.ASTRAL_SAPLING);
        blockWithItem(ModBlocks.ASTRAL_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.ASTRAL_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/astral-log"), new ResourceLocation(EmbrTrees.MODID, "block/astral-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.ASTRAL_WOOD.get(), blockTexture(ModBlocks.ASTRAL_LOG.get()), blockTexture(ModBlocks.ASTRAL_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_ASTRAL_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/astral-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/astral-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_ASTRAL_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/astral-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/astral-stripped-log"));
        blockWithItem(ModBlocks.ASTRAL_PLANKS);
        stairsBlock((StairBlock) ModBlocks.ASTRAL_STAIRS.get(), blockTexture(ModBlocks.ASTRAL_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.ASTRAL_SLAB.get(), blockTexture(ModBlocks.ASTRAL_PLANKS.get()), blockTexture(ModBlocks.ASTRAL_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.ASTRAL_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/astral-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/astral-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.ASTRAL_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/astral-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.ASTRAL_FENCE.get(), blockTexture(ModBlocks.ASTRAL_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.ASTRAL_FENCE_GATE.get(), blockTexture(ModBlocks.ASTRAL_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.ASTRAL_PRESSURE_PLATE.get(), blockTexture(ModBlocks.ASTRAL_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.ASTRAL_BUTTON.get(), models().button("embrtrees:astral-button", blockTexture(ModBlocks.ASTRAL_PLANKS.get())), models().buttonPressed("embrtrees:astral-button-pressed", blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.ASTRAL_SIGN.get(), (WallSignBlock)ModBlocks.ASTRAL_WALL_SIGN.get(), models().sign("embrtrees:astral-sign", blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASTRAL_LOG.get(), models().withExistingParent("embrtrees:astral-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.ASTRAL_WOOD.get(), models().withExistingParent("embrtrees:astral-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_ASTRAL_LOG.get(), models().withExistingParent("embrtrees:stripped-astral-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_ASTRAL_WOOD.get(), models().withExistingParent("embrtrees:stripped-astral-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.ASTRAL_STAIRS.get(), models().stairs("embrtrees:astral-stairs", blockTexture(ModBlocks.ASTRAL_PLANKS.get()), blockTexture(ModBlocks.ASTRAL_PLANKS.get()), blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASTRAL_SLAB.get(), models().slab("embrtrees:astral-slab", blockTexture(ModBlocks.ASTRAL_PLANKS.get()), blockTexture(ModBlocks.ASTRAL_PLANKS.get()), blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASTRAL_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:astral-trapdoor", blockTexture(ModBlocks.ASTRAL_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.ASTRAL_FENCE.get(), models().fenceInventory("embrtrees:astral-fence", blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASTRAL_FENCE_GATE.get(), models().fenceGate("embrtrees:astral-fence-gate", blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASTRAL_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:astral-pressure-plate", blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
        simpleBlockItem(ModBlocks.ASTRAL_BUTTON.get(), models().buttonInventory("embrtrees:astral-button-inventory", blockTexture(ModBlocks.ASTRAL_PLANKS.get())));
//BLOSSOM WOOD
        saplingBlock(ModBlocks.BLOSSOM_SAPLING);
        blockWithItem(ModBlocks.BLOSSOM_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.BLOSSOM_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/blossom-log"), new ResourceLocation(EmbrTrees.MODID, "block/blossom-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.BLOSSOM_WOOD.get(), blockTexture(ModBlocks.BLOSSOM_LOG.get()), blockTexture(ModBlocks.BLOSSOM_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_BLOSSOM_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/blossom-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/blossom-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_BLOSSOM_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/blossom-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/blossom-stripped-log"));
        blockWithItem(ModBlocks.BLOSSOM_PLANKS);
        stairsBlock((StairBlock) ModBlocks.BLOSSOM_STAIRS.get(), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.BLOSSOM_SLAB.get(), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.BLOSSOM_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/blossom-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/blossom-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.BLOSSOM_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/blossom-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.BLOSSOM_FENCE.get(), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.BLOSSOM_FENCE_GATE.get(), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.BLOSSOM_PRESSURE_PLATE.get(), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.BLOSSOM_BUTTON.get(), models().button("embrtrees:blossom-button", blockTexture(ModBlocks.BLOSSOM_PLANKS.get())), models().buttonPressed("embrtrees:blossom-button-pressed", blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.BLOSSOM_SIGN.get(), (WallSignBlock)ModBlocks.BLOSSOM_WALL_SIGN.get(), models().sign("embrtrees:blossom-sign", blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLOSSOM_LOG.get(), models().withExistingParent("embrtrees:blossom-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.BLOSSOM_WOOD.get(), models().withExistingParent("embrtrees:blossom-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_BLOSSOM_LOG.get(), models().withExistingParent("embrtrees:stripped-blossom-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_BLOSSOM_WOOD.get(), models().withExistingParent("embrtrees:stripped-blossom-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.BLOSSOM_STAIRS.get(), models().stairs("embrtrees:blossom-stairs", blockTexture(ModBlocks.BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLOSSOM_SLAB.get(), models().slab("embrtrees:blossom-slab", blockTexture(ModBlocks.BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLOSSOM_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:blossom-trapdoor", blockTexture(ModBlocks.BLOSSOM_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.BLOSSOM_FENCE.get(), models().fenceInventory("embrtrees:blossom-fence", blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLOSSOM_FENCE_GATE.get(), models().fenceGate("embrtrees:blossom-fence-gate", blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLOSSOM_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:blossom-pressure-plate", blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLOSSOM_BUTTON.get(), models().buttonInventory("embrtrees:blossom-button-inventory", blockTexture(ModBlocks.BLOSSOM_PLANKS.get())));
//VOID_BLOSSOM WOOD
        saplingBlock(ModBlocks.VOID_BLOSSOM_SAPLING);
        blockWithItem(ModBlocks.VOID_BLOSSOM_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.VOID_BLOSSOM_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-log"), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.VOID_BLOSSOM_WOOD.get(), blockTexture(ModBlocks.VOID_BLOSSOM_LOG.get()), blockTexture(ModBlocks.VOID_BLOSSOM_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_VOID_BLOSSOM_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_VOID_BLOSSOM_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-stripped-log"));
        blockWithItem(ModBlocks.VOID_BLOSSOM_PLANKS);
        stairsBlock((StairBlock) ModBlocks.VOID_BLOSSOM_STAIRS.get(), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.VOID_BLOSSOM_SLAB.get(), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.VOID_BLOSSOM_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.VOID_BLOSSOM_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/void-blossom-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.VOID_BLOSSOM_FENCE.get(), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.VOID_BLOSSOM_FENCE_GATE.get(), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.VOID_BLOSSOM_PRESSURE_PLATE.get(), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.VOID_BLOSSOM_BUTTON.get(), models().button("embrtrees:void-blossom-button", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())), models().buttonPressed("embrtrees:void-blossom-button-pressed", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.VOID_BLOSSOM_SIGN.get(), (WallSignBlock)ModBlocks.VOID_BLOSSOM_WALL_SIGN.get(), models().sign("embrtrees:void-blossom-sign", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_LOG.get(), models().withExistingParent("embrtrees:void-blossom-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_WOOD.get(), models().withExistingParent("embrtrees:void-blossom-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_VOID_BLOSSOM_LOG.get(), models().withExistingParent("embrtrees:stripped-void-blossom-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_VOID_BLOSSOM_WOOD.get(), models().withExistingParent("embrtrees:stripped-void-blossom-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_STAIRS.get(), models().stairs("embrtrees:void-blossom-stairs", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_SLAB.get(), models().slab("embrtrees:void-blossom-slab", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get()), blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:void-blossom-trapdoor", blockTexture(ModBlocks.VOID_BLOSSOM_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_FENCE.get(), models().fenceInventory("embrtrees:void-blossom-fence", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_FENCE_GATE.get(), models().fenceGate("embrtrees:void-blossom-fence-gate", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:void-blossom-pressure-plate", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
        simpleBlockItem(ModBlocks.VOID_BLOSSOM_BUTTON.get(), models().buttonInventory("embrtrees:void-blossom-button-inventory", blockTexture(ModBlocks.VOID_BLOSSOM_PLANKS.get())));
//MAHOGANY WOOD
        saplingBlock(ModBlocks.MAHOGANY_SAPLING);
        blockWithItem(ModBlocks.MAHOGANY_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.MAHOGANY_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-log"), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.MAHOGANY_WOOD.get(), blockTexture(ModBlocks.MAHOGANY_LOG.get()), blockTexture(ModBlocks.MAHOGANY_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_MAHOGANY_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_MAHOGANY_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-stripped-log"));
        blockWithItem(ModBlocks.MAHOGANY_PLANKS);
        stairsBlock((StairBlock) ModBlocks.MAHOGANY_STAIRS.get(), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.MAHOGANY_SLAB.get(), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.MAHOGANY_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.MAHOGANY_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/mahogany-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.MAHOGANY_FENCE.get(), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.MAHOGANY_FENCE_GATE.get(), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.MAHOGANY_PRESSURE_PLATE.get(), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.MAHOGANY_BUTTON.get(), models().button("embrtrees:mahogany-button", blockTexture(ModBlocks.MAHOGANY_PLANKS.get())), models().buttonPressed("embrtrees:mahogany-button-pressed", blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.MAHOGANY_SIGN.get(), (WallSignBlock)ModBlocks.MAHOGANY_WALL_SIGN.get(), models().sign("embrtrees:mahogany-sign", blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
        simpleBlockItem(ModBlocks.MAHOGANY_LOG.get(), models().withExistingParent("embrtrees:mahogany-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.MAHOGANY_WOOD.get(), models().withExistingParent("embrtrees:mahogany-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_MAHOGANY_LOG.get(), models().withExistingParent("embrtrees:stripped-mahogany-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_MAHOGANY_WOOD.get(), models().withExistingParent("embrtrees:stripped-mahogany-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.MAHOGANY_STAIRS.get(), models().stairs("embrtrees:mahogany-stairs", blockTexture(ModBlocks.MAHOGANY_PLANKS.get()), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()), blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
        simpleBlockItem(ModBlocks.MAHOGANY_SLAB.get(), models().slab("embrtrees:mahogany-slab", blockTexture(ModBlocks.MAHOGANY_PLANKS.get()), blockTexture(ModBlocks.MAHOGANY_PLANKS.get()), blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
        simpleBlockItem(ModBlocks.MAHOGANY_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:mahogany-trapdoor", blockTexture(ModBlocks.MAHOGANY_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.MAHOGANY_FENCE.get(), models().fenceInventory("embrtrees:mahogany-fence", blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
        simpleBlockItem(ModBlocks.MAHOGANY_FENCE_GATE.get(), models().fenceGate("embrtrees:mahogany-fence-gate", blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
        simpleBlockItem(ModBlocks.MAHOGANY_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:mahogany-pressure-plate", blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
        simpleBlockItem(ModBlocks.MAHOGANY_BUTTON.get(), models().buttonInventory("embrtrees:mahogany-button-inventory", blockTexture(ModBlocks.MAHOGANY_PLANKS.get())));
//OCEANIC WOOD
        saplingBlock(ModBlocks.OCEANIC_SAPLING);
        blockWithItem(ModBlocks.OCEANIC_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.OCEANIC_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-log"), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.OCEANIC_WOOD.get(), blockTexture(ModBlocks.OCEANIC_LOG.get()), blockTexture(ModBlocks.OCEANIC_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_OCEANIC_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_OCEANIC_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-stripped-log"));
        blockWithItem(ModBlocks.OCEANIC_PLANKS);
        stairsBlock((StairBlock) ModBlocks.OCEANIC_STAIRS.get(), blockTexture(ModBlocks.OCEANIC_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.OCEANIC_SLAB.get(), blockTexture(ModBlocks.OCEANIC_PLANKS.get()), blockTexture(ModBlocks.OCEANIC_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.OCEANIC_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.OCEANIC_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/oceanic-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.OCEANIC_FENCE.get(), blockTexture(ModBlocks.OCEANIC_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.OCEANIC_FENCE_GATE.get(), blockTexture(ModBlocks.OCEANIC_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.OCEANIC_PRESSURE_PLATE.get(), blockTexture(ModBlocks.OCEANIC_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.OCEANIC_BUTTON.get(), models().button("embrtrees:oceanic-button", blockTexture(ModBlocks.OCEANIC_PLANKS.get())), models().buttonPressed("embrtrees:oceanic-button-pressed", blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.OCEANIC_SIGN.get(), (WallSignBlock)ModBlocks.OCEANIC_WALL_SIGN.get(), models().sign("embrtrees:oceanic-sign", blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.OCEANIC_LOG.get(), models().withExistingParent("embrtrees:oceanic-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.OCEANIC_WOOD.get(), models().withExistingParent("embrtrees:oceanic-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_OCEANIC_LOG.get(), models().withExistingParent("embrtrees:stripped-oceanic-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_OCEANIC_WOOD.get(), models().withExistingParent("embrtrees:stripped-oceanic-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.OCEANIC_STAIRS.get(), models().stairs("embrtrees:oceanic-stairs", blockTexture(ModBlocks.OCEANIC_PLANKS.get()), blockTexture(ModBlocks.OCEANIC_PLANKS.get()), blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.OCEANIC_SLAB.get(), models().slab("embrtrees:oceanic-slab", blockTexture(ModBlocks.OCEANIC_PLANKS.get()), blockTexture(ModBlocks.OCEANIC_PLANKS.get()), blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.OCEANIC_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:oceanic-trapdoor", blockTexture(ModBlocks.OCEANIC_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.OCEANIC_FENCE.get(), models().fenceInventory("embrtrees:oceanic-fence", blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.OCEANIC_FENCE_GATE.get(), models().fenceGate("embrtrees:oceanic-fence-gate", blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.OCEANIC_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:oceanic-pressure-plate", blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.OCEANIC_BUTTON.get(), models().buttonInventory("embrtrees:oceanic-button-inventory", blockTexture(ModBlocks.OCEANIC_PLANKS.get())));
//QUARTZWOOD WOOD
        saplingBlock(ModBlocks.QUARTZWOOD_SAPLING);
        blockWithItem(ModBlocks.QUARTZWOOD_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.QUARTZWOOD_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-log"), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.QUARTZWOOD_WOOD.get(), blockTexture(ModBlocks.QUARTZWOOD_LOG.get()), blockTexture(ModBlocks.QUARTZWOOD_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_QUARTZWOOD_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_QUARTZWOOD_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-stripped-log"));
        blockWithItem(ModBlocks.QUARTZWOOD_PLANKS);
        stairsBlock((StairBlock) ModBlocks.QUARTZWOOD_STAIRS.get(), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.QUARTZWOOD_SLAB.get(), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.QUARTZWOOD_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.QUARTZWOOD_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/quartzwood-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.QUARTZWOOD_FENCE.get(), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.QUARTZWOOD_FENCE_GATE.get(), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.QUARTZWOOD_PRESSURE_PLATE.get(), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.QUARTZWOOD_BUTTON.get(), models().button("embrtrees:quartzwood-button", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())), models().buttonPressed("embrtrees:quartzwood-button-pressed", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.QUARTZWOOD_SIGN.get(), (WallSignBlock)ModBlocks.QUARTZWOOD_WALL_SIGN.get(), models().sign("embrtrees:quartzwood-sign", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.QUARTZWOOD_LOG.get(), models().withExistingParent("embrtrees:quartzwood-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.QUARTZWOOD_WOOD.get(), models().withExistingParent("embrtrees:quartzwood-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_QUARTZWOOD_LOG.get(), models().withExistingParent("embrtrees:stripped-quartzwood-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_QUARTZWOOD_WOOD.get(), models().withExistingParent("embrtrees:stripped-quartzwood-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.QUARTZWOOD_STAIRS.get(), models().stairs("embrtrees:quartzwood-stairs", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.QUARTZWOOD_SLAB.get(), models().slab("embrtrees:quartzwood-slab", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get()), blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.QUARTZWOOD_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:quartzwood-trapdoor", blockTexture(ModBlocks.QUARTZWOOD_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.QUARTZWOOD_FENCE.get(), models().fenceInventory("embrtrees:quartzwood-fence", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.QUARTZWOOD_FENCE_GATE.get(), models().fenceGate("embrtrees:quartzwood-fence-gate", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.QUARTZWOOD_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:quartzwood-pressure-plate", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.QUARTZWOOD_BUTTON.get(), models().buttonInventory("embrtrees:quartzwood-button-inventory", blockTexture(ModBlocks.QUARTZWOOD_PLANKS.get())));
//VAMPIRIC WOOD
        saplingBlock(ModBlocks.VAMPIRIC_SAPLING);
        blockWithItem(ModBlocks.VAMPIRIC_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.VAMPIRIC_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-log"), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.VAMPIRIC_WOOD.get(), blockTexture(ModBlocks.VAMPIRIC_LOG.get()), blockTexture(ModBlocks.VAMPIRIC_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_VAMPIRIC_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_VAMPIRIC_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-stripped-log"));
        blockWithItem(ModBlocks.VAMPIRIC_PLANKS);
        stairsBlock((StairBlock) ModBlocks.VAMPIRIC_STAIRS.get(), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.VAMPIRIC_SLAB.get(), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.VAMPIRIC_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.VAMPIRIC_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/vampiric-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.VAMPIRIC_FENCE.get(), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.VAMPIRIC_FENCE_GATE.get(), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.VAMPIRIC_PRESSURE_PLATE.get(), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.VAMPIRIC_BUTTON.get(), models().button("embrtrees:vampiric-button", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())), models().buttonPressed("embrtrees:vampiric-button-pressed", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.VAMPIRIC_SIGN.get(), (WallSignBlock)ModBlocks.VAMPIRIC_WALL_SIGN.get(), models().sign("embrtrees:vampiric-sign", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.VAMPIRIC_LOG.get(), models().withExistingParent("embrtrees:vampiric-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.VAMPIRIC_WOOD.get(), models().withExistingParent("embrtrees:vampiric-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_VAMPIRIC_LOG.get(), models().withExistingParent("embrtrees:stripped-vampiric-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_VAMPIRIC_WOOD.get(), models().withExistingParent("embrtrees:stripped-vampiric-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.VAMPIRIC_STAIRS.get(), models().stairs("embrtrees:vampiric-stairs", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.VAMPIRIC_SLAB.get(), models().slab("embrtrees:vampiric-slab", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get()), blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.VAMPIRIC_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:vampiric-trapdoor", blockTexture(ModBlocks.VAMPIRIC_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.VAMPIRIC_FENCE.get(), models().fenceInventory("embrtrees:vampiric-fence", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.VAMPIRIC_FENCE_GATE.get(), models().fenceGate("embrtrees:vampiric-fence-gate", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.VAMPIRIC_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:vampiric-pressure-plate", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
        simpleBlockItem(ModBlocks.VAMPIRIC_BUTTON.get(), models().buttonInventory("embrtrees:vampiric-button-inventory", blockTexture(ModBlocks.VAMPIRIC_PLANKS.get())));
//WILLOW WOOD
        saplingBlock(ModBlocks.WILLOW_SAPLING);
        blockWithItem(ModBlocks.WILLOW_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.WILLOW_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/willow-log"), new ResourceLocation(EmbrTrees.MODID, "block/willow-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.WILLOW_WOOD.get(), blockTexture(ModBlocks.WILLOW_LOG.get()), blockTexture(ModBlocks.WILLOW_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_WILLOW_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/willow-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/willow-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_WILLOW_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/willow-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/willow-stripped-log"));
        blockWithItem(ModBlocks.WILLOW_PLANKS);
        stairsBlock((StairBlock) ModBlocks.WILLOW_STAIRS.get(), blockTexture(ModBlocks.WILLOW_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.WILLOW_SLAB.get(), blockTexture(ModBlocks.WILLOW_PLANKS.get()), blockTexture(ModBlocks.WILLOW_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.WILLOW_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/willow-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/willow-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.WILLOW_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/willow-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.WILLOW_FENCE.get(), blockTexture(ModBlocks.WILLOW_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.WILLOW_FENCE_GATE.get(), blockTexture(ModBlocks.WILLOW_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.WILLOW_PRESSURE_PLATE.get(), blockTexture(ModBlocks.WILLOW_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.WILLOW_BUTTON.get(), models().button("embrtrees:willow-button", blockTexture(ModBlocks.WILLOW_PLANKS.get())), models().buttonPressed("embrtrees:willow-button-pressed", blockTexture(ModBlocks.WILLOW_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.WILLOW_SIGN.get(), (WallSignBlock)ModBlocks.WILLOW_WALL_SIGN.get(), models().sign("embrtrees:willow-sign", blockTexture(ModBlocks.WILLOW_PLANKS.get())));
        simpleBlockItem(ModBlocks.WILLOW_LOG.get(), models().withExistingParent("embrtrees:willow-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.WILLOW_WOOD.get(), models().withExistingParent("embrtrees:willow-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_WILLOW_LOG.get(), models().withExistingParent("embrtrees:stripped-willow-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_WILLOW_WOOD.get(), models().withExistingParent("embrtrees:stripped-willow-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.WILLOW_STAIRS.get(), models().stairs("embrtrees:willow-stairs", blockTexture(ModBlocks.WILLOW_PLANKS.get()), blockTexture(ModBlocks.WILLOW_PLANKS.get()), blockTexture(ModBlocks.WILLOW_PLANKS.get())));
        simpleBlockItem(ModBlocks.WILLOW_SLAB.get(), models().slab("embrtrees:willow-slab", blockTexture(ModBlocks.WILLOW_PLANKS.get()), blockTexture(ModBlocks.WILLOW_PLANKS.get()), blockTexture(ModBlocks.WILLOW_PLANKS.get())));
        simpleBlockItem(ModBlocks.WILLOW_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:willow-trapdoor", blockTexture(ModBlocks.WILLOW_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.WILLOW_FENCE.get(), models().fenceInventory("embrtrees:willow-fence", blockTexture(ModBlocks.WILLOW_PLANKS.get())));
        simpleBlockItem(ModBlocks.WILLOW_FENCE_GATE.get(), models().fenceGate("embrtrees:willow-fence-gate", blockTexture(ModBlocks.WILLOW_PLANKS.get())));
        simpleBlockItem(ModBlocks.WILLOW_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:willow-pressure-plate", blockTexture(ModBlocks.WILLOW_PLANKS.get())));
        simpleBlockItem(ModBlocks.WILLOW_BUTTON.get(), models().buttonInventory("embrtrees:willow-button-inventory", blockTexture(ModBlocks.WILLOW_PLANKS.get())));
//BLACKWOOD WOOD
        saplingBlock(ModBlocks.BLACKWOOD_SAPLING);
        blockWithItem(ModBlocks.BLACKWOOD_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.BLACKWOOD_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-log"), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.BLACKWOOD_WOOD.get(), blockTexture(ModBlocks.BLACKWOOD_LOG.get()), blockTexture(ModBlocks.BLACKWOOD_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_BLACKWOOD_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_BLACKWOOD_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-stripped-log"));
        blockWithItem(ModBlocks.BLACKWOOD_PLANKS);
        stairsBlock((StairBlock) ModBlocks.BLACKWOOD_STAIRS.get(), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.BLACKWOOD_SLAB.get(), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.BLACKWOOD_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.BLACKWOOD_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/blackwood-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.BLACKWOOD_FENCE.get(), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.BLACKWOOD_FENCE_GATE.get(), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.BLACKWOOD_PRESSURE_PLATE.get(), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.BLACKWOOD_BUTTON.get(), models().button("embrtrees:blackwood-button", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())), models().buttonPressed("embrtrees:blackwood-button-pressed", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.BLACKWOOD_SIGN.get(), (WallSignBlock)ModBlocks.BLACKWOOD_WALL_SIGN.get(), models().sign("embrtrees:blackwood-sign", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLACKWOOD_LOG.get(), models().withExistingParent("embrtrees:blackwood-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.BLACKWOOD_WOOD.get(), models().withExistingParent("embrtrees:blackwood-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_BLACKWOOD_LOG.get(), models().withExistingParent("embrtrees:stripped-blackwood-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_BLACKWOOD_WOOD.get(), models().withExistingParent("embrtrees:stripped-blackwood-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.BLACKWOOD_STAIRS.get(), models().stairs("embrtrees:blackwood-stairs", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLACKWOOD_SLAB.get(), models().slab("embrtrees:blackwood-slab", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get()), blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLACKWOOD_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:blackwood-trapdoor", blockTexture(ModBlocks.BLACKWOOD_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.BLACKWOOD_FENCE.get(), models().fenceInventory("embrtrees:blackwood-fence", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLACKWOOD_FENCE_GATE.get(), models().fenceGate("embrtrees:blackwood-fence-gate", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLACKWOOD_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:blackwood-pressure-plate", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.BLACKWOOD_BUTTON.get(), models().buttonInventory("embrtrees:blackwood-button-inventory", blockTexture(ModBlocks.BLACKWOOD_PLANKS.get())));
//WALNUT WOOD
        saplingBlock(ModBlocks.WALNUT_SAPLING);
        blockWithItem(ModBlocks.WALNUT_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.WALNUT_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/walnut-log"), new ResourceLocation(EmbrTrees.MODID, "block/walnut-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.WALNUT_WOOD.get(), blockTexture(ModBlocks.WALNUT_LOG.get()), blockTexture(ModBlocks.WALNUT_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_WALNUT_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/walnut-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/walnut-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_WALNUT_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/walnut-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/walnut-stripped-log"));
        blockWithItem(ModBlocks.WALNUT_PLANKS);
        stairsBlock((StairBlock) ModBlocks.WALNUT_STAIRS.get(), blockTexture(ModBlocks.WALNUT_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.WALNUT_SLAB.get(), blockTexture(ModBlocks.WALNUT_PLANKS.get()), blockTexture(ModBlocks.WALNUT_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.WALNUT_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/walnut-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/walnut-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.WALNUT_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/walnut-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.WALNUT_FENCE.get(), blockTexture(ModBlocks.WALNUT_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.WALNUT_FENCE_GATE.get(), blockTexture(ModBlocks.WALNUT_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.WALNUT_PRESSURE_PLATE.get(), blockTexture(ModBlocks.WALNUT_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.WALNUT_BUTTON.get(), models().button("embrtrees:walnut-button", blockTexture(ModBlocks.WALNUT_PLANKS.get())), models().buttonPressed("embrtrees:walnut-button-pressed", blockTexture(ModBlocks.WALNUT_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.WALNUT_SIGN.get(), (WallSignBlock)ModBlocks.WALNUT_WALL_SIGN.get(), models().sign("embrtrees:walnut-sign", blockTexture(ModBlocks.WALNUT_PLANKS.get())));
        simpleBlockItem(ModBlocks.WALNUT_LOG.get(), models().withExistingParent("embrtrees:walnut-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.WALNUT_WOOD.get(), models().withExistingParent("embrtrees:walnut-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_WALNUT_LOG.get(), models().withExistingParent("embrtrees:stripped-walnut-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_WALNUT_WOOD.get(), models().withExistingParent("embrtrees:stripped-walnut-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.WALNUT_STAIRS.get(), models().stairs("embrtrees:walnut-stairs", blockTexture(ModBlocks.WALNUT_PLANKS.get()), blockTexture(ModBlocks.WALNUT_PLANKS.get()), blockTexture(ModBlocks.WALNUT_PLANKS.get())));
        simpleBlockItem(ModBlocks.WALNUT_SLAB.get(), models().slab("embrtrees:walnut-slab", blockTexture(ModBlocks.WALNUT_PLANKS.get()), blockTexture(ModBlocks.WALNUT_PLANKS.get()), blockTexture(ModBlocks.WALNUT_PLANKS.get())));
        simpleBlockItem(ModBlocks.WALNUT_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:walnut-trapdoor", blockTexture(ModBlocks.WALNUT_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.WALNUT_FENCE.get(), models().fenceInventory("embrtrees:walnut-fence", blockTexture(ModBlocks.WALNUT_PLANKS.get())));
        simpleBlockItem(ModBlocks.WALNUT_FENCE_GATE.get(), models().fenceGate("embrtrees:walnut-fence-gate", blockTexture(ModBlocks.WALNUT_PLANKS.get())));
        simpleBlockItem(ModBlocks.WALNUT_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:walnut-pressure-plate", blockTexture(ModBlocks.WALNUT_PLANKS.get())));
        simpleBlockItem(ModBlocks.WALNUT_BUTTON.get(), models().buttonInventory("embrtrees:walnut-button-inventory", blockTexture(ModBlocks.WALNUT_PLANKS.get())));
//HEARTWOOD WOOD
        saplingBlock(ModBlocks.HEARTWOOD_SAPLING);
        blockWithItem(ModBlocks.HEARTWOOD_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.HEARTWOOD_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-log"), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.HEARTWOOD_WOOD.get(), blockTexture(ModBlocks.HEARTWOOD_LOG.get()), blockTexture(ModBlocks.HEARTWOOD_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_HEARTWOOD_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_HEARTWOOD_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-stripped-log"));
        blockWithItem(ModBlocks.HEARTWOOD_PLANKS);
        stairsBlock((StairBlock) ModBlocks.HEARTWOOD_STAIRS.get(), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.HEARTWOOD_SLAB.get(), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.HEARTWOOD_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.HEARTWOOD_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/heartwood-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.HEARTWOOD_FENCE.get(), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.HEARTWOOD_FENCE_GATE.get(), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.HEARTWOOD_PRESSURE_PLATE.get(), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.HEARTWOOD_BUTTON.get(), models().button("embrtrees:heartwood-button", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())), models().buttonPressed("embrtrees:heartwood-button-pressed", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.HEARTWOOD_SIGN.get(), (WallSignBlock)ModBlocks.HEARTWOOD_WALL_SIGN.get(), models().sign("embrtrees:heartwood-sign", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.HEARTWOOD_LOG.get(), models().withExistingParent("embrtrees:heartwood-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.HEARTWOOD_WOOD.get(), models().withExistingParent("embrtrees:heartwood-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_HEARTWOOD_LOG.get(), models().withExistingParent("embrtrees:stripped-heartwood-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_HEARTWOOD_WOOD.get(), models().withExistingParent("embrtrees:stripped-heartwood-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.HEARTWOOD_STAIRS.get(), models().stairs("embrtrees:heartwood-stairs", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.HEARTWOOD_SLAB.get(), models().slab("embrtrees:heartwood-slab", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get()), blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.HEARTWOOD_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:heartwood-trapdoor", blockTexture(ModBlocks.HEARTWOOD_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.HEARTWOOD_FENCE.get(), models().fenceInventory("embrtrees:heartwood-fence", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.HEARTWOOD_FENCE_GATE.get(), models().fenceGate("embrtrees:heartwood-fence-gate", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.HEARTWOOD_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:heartwood-pressure-plate", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
        simpleBlockItem(ModBlocks.HEARTWOOD_BUTTON.get(), models().buttonInventory("embrtrees:heartwood-button-inventory", blockTexture(ModBlocks.HEARTWOOD_PLANKS.get())));
//SUNRISE WOOD
        saplingBlock(ModBlocks.SUNRISE_SAPLING);
        blockWithItem(ModBlocks.SUNRISE_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.SUNRISE_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-log"), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.SUNRISE_WOOD.get(), blockTexture(ModBlocks.SUNRISE_LOG.get()), blockTexture(ModBlocks.SUNRISE_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_SUNRISE_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_SUNRISE_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-stripped-log"));
        blockWithItem(ModBlocks.SUNRISE_PLANKS);
        stairsBlock((StairBlock) ModBlocks.SUNRISE_STAIRS.get(), blockTexture(ModBlocks.SUNRISE_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.SUNRISE_SLAB.get(), blockTexture(ModBlocks.SUNRISE_PLANKS.get()), blockTexture(ModBlocks.SUNRISE_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.SUNRISE_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.SUNRISE_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/sunrise-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.SUNRISE_FENCE.get(), blockTexture(ModBlocks.SUNRISE_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.SUNRISE_FENCE_GATE.get(), blockTexture(ModBlocks.SUNRISE_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.SUNRISE_PRESSURE_PLATE.get(), blockTexture(ModBlocks.SUNRISE_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.SUNRISE_BUTTON.get(), models().button("embrtrees:sunrise-button", blockTexture(ModBlocks.SUNRISE_PLANKS.get())), models().buttonPressed("embrtrees:sunrise-button-pressed", blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.SUNRISE_SIGN.get(), (WallSignBlock)ModBlocks.SUNRISE_WALL_SIGN.get(), models().sign("embrtrees:sunrise-sign", blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
        simpleBlockItem(ModBlocks.SUNRISE_LOG.get(), models().withExistingParent("embrtrees:sunrise-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.SUNRISE_WOOD.get(), models().withExistingParent("embrtrees:sunrise-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_SUNRISE_LOG.get(), models().withExistingParent("embrtrees:stripped-sunrise-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_SUNRISE_WOOD.get(), models().withExistingParent("embrtrees:stripped-sunrise-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.SUNRISE_STAIRS.get(), models().stairs("embrtrees:sunrise-stairs", blockTexture(ModBlocks.SUNRISE_PLANKS.get()), blockTexture(ModBlocks.SUNRISE_PLANKS.get()), blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
        simpleBlockItem(ModBlocks.SUNRISE_SLAB.get(), models().slab("embrtrees:sunrise-slab", blockTexture(ModBlocks.SUNRISE_PLANKS.get()), blockTexture(ModBlocks.SUNRISE_PLANKS.get()), blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
        simpleBlockItem(ModBlocks.SUNRISE_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:sunrise-trapdoor", blockTexture(ModBlocks.SUNRISE_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.SUNRISE_FENCE.get(), models().fenceInventory("embrtrees:sunrise-fence", blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
        simpleBlockItem(ModBlocks.SUNRISE_FENCE_GATE.get(), models().fenceGate("embrtrees:sunrise-fence-gate", blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
        simpleBlockItem(ModBlocks.SUNRISE_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:sunrise-pressure-plate", blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
        simpleBlockItem(ModBlocks.SUNRISE_BUTTON.get(), models().buttonInventory("embrtrees:sunrise-button-inventory", blockTexture(ModBlocks.SUNRISE_PLANKS.get())));
//ERROR WOOD
        saplingBlock(ModBlocks.ERROR_SAPLING);
        blockWithItem(ModBlocks.ERROR_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.ERROR_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/error-log"), new ResourceLocation(EmbrTrees.MODID, "block/error-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.ERROR_WOOD.get(), blockTexture(ModBlocks.ERROR_LOG.get()), blockTexture(ModBlocks.ERROR_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_ERROR_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/error-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/error-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_ERROR_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/error-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/error-stripped-log"));
        blockWithItem(ModBlocks.ERROR_PLANKS);
        stairsBlock((StairBlock) ModBlocks.ERROR_STAIRS.get(), blockTexture(ModBlocks.ERROR_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.ERROR_SLAB.get(), blockTexture(ModBlocks.ERROR_PLANKS.get()), blockTexture(ModBlocks.ERROR_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.ERROR_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/error-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/error-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.ERROR_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/error-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.ERROR_FENCE.get(), blockTexture(ModBlocks.ERROR_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.ERROR_FENCE_GATE.get(), blockTexture(ModBlocks.ERROR_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.ERROR_PRESSURE_PLATE.get(), blockTexture(ModBlocks.ERROR_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.ERROR_BUTTON.get(), models().button("embrtrees:error-button", blockTexture(ModBlocks.ERROR_PLANKS.get())), models().buttonPressed("embrtrees:error-button-pressed", blockTexture(ModBlocks.ERROR_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.ERROR_SIGN.get(), (WallSignBlock)ModBlocks.ERROR_WALL_SIGN.get(), models().sign("embrtrees:error-sign", blockTexture(ModBlocks.ERROR_PLANKS.get())));
        simpleBlockItem(ModBlocks.ERROR_LOG.get(), models().withExistingParent("embrtrees:error-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.ERROR_WOOD.get(), models().withExistingParent("embrtrees:error-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_ERROR_LOG.get(), models().withExistingParent("embrtrees:stripped-error-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_ERROR_WOOD.get(), models().withExistingParent("embrtrees:stripped-error-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.ERROR_STAIRS.get(), models().stairs("embrtrees:error-stairs", blockTexture(ModBlocks.ERROR_PLANKS.get()), blockTexture(ModBlocks.ERROR_PLANKS.get()), blockTexture(ModBlocks.ERROR_PLANKS.get())));
        simpleBlockItem(ModBlocks.ERROR_SLAB.get(), models().slab("embrtrees:error-slab", blockTexture(ModBlocks.ERROR_PLANKS.get()), blockTexture(ModBlocks.ERROR_PLANKS.get()), blockTexture(ModBlocks.ERROR_PLANKS.get())));
        simpleBlockItem(ModBlocks.ERROR_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:error-trapdoor", blockTexture(ModBlocks.ERROR_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.ERROR_FENCE.get(), models().fenceInventory("embrtrees:error-fence", blockTexture(ModBlocks.ERROR_PLANKS.get())));
        simpleBlockItem(ModBlocks.ERROR_FENCE_GATE.get(), models().fenceGate("embrtrees:error-fence-gate", blockTexture(ModBlocks.ERROR_PLANKS.get())));
        simpleBlockItem(ModBlocks.ERROR_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:error-pressure-plate", blockTexture(ModBlocks.ERROR_PLANKS.get())));
        simpleBlockItem(ModBlocks.ERROR_BUTTON.get(), models().buttonInventory("embrtrees:error-button-inventory", blockTexture(ModBlocks.ERROR_PLANKS.get())));
//CYAN WOOD
        saplingBlock(ModBlocks.CYAN_SAPLING);
        blockWithItem(ModBlocks.CYAN_LEAVES);
        axisBlock((RotatedPillarBlock) ModBlocks.CYAN_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/cyan-log"), new ResourceLocation(EmbrTrees.MODID, "block/cyan-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.CYAN_WOOD.get(), blockTexture(ModBlocks.CYAN_LOG.get()), blockTexture(ModBlocks.CYAN_LOG.get()));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_CYAN_LOG.get(), new ResourceLocation(EmbrTrees.MODID, "block/cyan-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/cyan-stripped-log-top"));
        axisBlock((RotatedPillarBlock) ModBlocks.STRIPPED_CYAN_WOOD.get(), new ResourceLocation(EmbrTrees.MODID, "block/cyan-stripped-log"), new ResourceLocation(EmbrTrees.MODID, "block/cyan-stripped-log"));
        blockWithItem(ModBlocks.CYAN_PLANKS);
        stairsBlock((StairBlock) ModBlocks.CYAN_STAIRS.get(), blockTexture(ModBlocks.CYAN_PLANKS.get()));
        slabBlock((SlabBlock) ModBlocks.CYAN_SLAB.get(), blockTexture(ModBlocks.CYAN_PLANKS.get()), blockTexture(ModBlocks.CYAN_PLANKS.get()));
        doorBlockWithRenderType((DoorBlock) ModBlocks.CYAN_DOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/cyan-door-lower"), new ResourceLocation(EmbrTrees.MODID, "block/cyan-door-upper"), "cutout");
        trapdoorBlockWithRenderType((TrapDoorBlock) ModBlocks.CYAN_TRAPDOOR.get(), new ResourceLocation(EmbrTrees.MODID, "block/cyan-trapdoor"), true, "cutout");
        fenceBlock((FenceBlock) ModBlocks.CYAN_FENCE.get(), blockTexture(ModBlocks.CYAN_PLANKS.get()));
        fenceGateBlock((FenceGateBlock) ModBlocks.CYAN_FENCE_GATE.get(), blockTexture(ModBlocks.CYAN_PLANKS.get()));
        pressurePlateBlock((PressurePlateBlock)ModBlocks.CYAN_PRESSURE_PLATE.get(), blockTexture(ModBlocks.CYAN_PLANKS.get()));
        buttonBlock((ButtonBlock)ModBlocks.CYAN_BUTTON.get(), models().button("embrtrees:cyan-button", blockTexture(ModBlocks.CYAN_PLANKS.get())), models().buttonPressed("embrtrees:cyan-button-pressed", blockTexture(ModBlocks.CYAN_PLANKS.get())));
        signBlock((StandingSignBlock)ModBlocks.CYAN_SIGN.get(), (WallSignBlock)ModBlocks.CYAN_WALL_SIGN.get(), models().sign("embrtrees:cyan-sign", blockTexture(ModBlocks.CYAN_PLANKS.get())));
        simpleBlockItem(ModBlocks.CYAN_LOG.get(), models().withExistingParent("embrtrees:cyan-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.CYAN_WOOD.get(), models().withExistingParent("embrtrees:cyan-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_CYAN_LOG.get(), models().withExistingParent("embrtrees:stripped-cyan-log", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.STRIPPED_CYAN_WOOD.get(), models().withExistingParent("embrtrees:stripped-cyan-wood", "minecraft:block/cube_column"));
        simpleBlockItem(ModBlocks.CYAN_STAIRS.get(), models().stairs("embrtrees:cyan-stairs", blockTexture(ModBlocks.CYAN_PLANKS.get()), blockTexture(ModBlocks.CYAN_PLANKS.get()), blockTexture(ModBlocks.CYAN_PLANKS.get())));
        simpleBlockItem(ModBlocks.CYAN_SLAB.get(), models().slab("embrtrees:cyan-slab", blockTexture(ModBlocks.CYAN_PLANKS.get()), blockTexture(ModBlocks.CYAN_PLANKS.get()), blockTexture(ModBlocks.CYAN_PLANKS.get())));
        simpleBlockItem(ModBlocks.CYAN_TRAPDOOR.get(), models().trapdoorBottom("embrtrees:cyan-trapdoor", blockTexture(ModBlocks.CYAN_TRAPDOOR.get())));
        simpleBlockItem(ModBlocks.CYAN_FENCE.get(), models().fenceInventory("embrtrees:cyan-fence", blockTexture(ModBlocks.CYAN_PLANKS.get())));
        simpleBlockItem(ModBlocks.CYAN_FENCE_GATE.get(), models().fenceGate("embrtrees:cyan-fence-gate", blockTexture(ModBlocks.CYAN_PLANKS.get())));
        simpleBlockItem(ModBlocks.CYAN_PRESSURE_PLATE.get(), models().pressurePlate("embrtrees:cyan-pressure-plate", blockTexture(ModBlocks.CYAN_PLANKS.get())));
        simpleBlockItem(ModBlocks.CYAN_BUTTON.get(), models().buttonInventory("embrtrees:cyan-button-inventory", blockTexture(ModBlocks.CYAN_PLANKS.get())));

    }

    private void blockWithItem(RegistryObject<Block> blockRegistryObject) {
        simpleBlockWithItem(blockRegistryObject.get(), cubeAll(blockRegistryObject.get()));
    }

    private void saplingBlock(RegistryObject<Block> blockRegistryObject) {
        simpleBlock(blockRegistryObject.get(),
                models().cross(ForgeRegistries.BLOCKS.getKey(blockRegistryObject.get()).getPath(), blockTexture(blockRegistryObject.get())).renderType("cutout"));
    }
}
